### ISSUE TITLE
Missing Package Scoping on Android

### ISSUE THREAD

**Issue by tschanz-pcv** [Karthi27p/react-native-plist#3]
The package name in the Android parts is still the default "com.reactlibrary" which should at least be scoped to something like "com.reactlibrary.rnplist" or similar, otherwise it's easy to conflict with other libraries that didn't bother to update the defaults.

As this does nothing on Android, maybe just remove that part.

**Comment by Karthi27p** [comment]
Issue Resolved - Removed package scoping on android and released v1.0.1
